### ISSUE TITLE
Todo list for release

### ISSUE THREAD

**Issue by harry900831** [NTHU-CP/NTHU-CPP#105]
- [ ] foreword
- [ ] Introduction to CP an NTHU CP Team
- [ ] How to Practice
- [ ] Calendar
- [ ] Update Contest information
- [ ] Update contribution note
- [ ] Update useful resources
- [ ] doc for clerical work if you want to host an event or apply for reimbursement
- [ ] C++ programming tips
- [ ] Give each topic an intro.md
